### model
model_name_or_path: Qwen/Qwen2.5-Omni-3B
adapter_name_or_path: saves/qwen2_5omni-3b/lora/sft
template: qwen2_omni
trust_remote_code: true

### export
export_dir: output/qwen2_5omni-3b
export_size: 5
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false